<a href="https://colab.research.google.com/github/NATHAN-70/AI-ML/blob/main/knn_imputers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/train.csv")
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [ ]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["trans_date_trans_time"]=le.fit_transform(df["trans_date_trans_time"])
df["merchant"]=le.fit_transform(df["merchant"])
df["category"]=le.fit_transform(df["category"])
df["first"]=le.fit_transform(df["first"])
df["last"]=le.fit_transform(df["last"])
df["gender"]=le.fit_transform(df["gender"])
df["city"]=le.fit_transform(df["city"])
df["state"]=le.fit_transform(df["state"])
df["job"]=le.fit_transform(df["job"])
df["dob"]=le.fit_transform(df["dob"])
df["trans_num"]=le.fit_transform(df["trans_num"])
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,-0.316692,514,8,-0.407826,162,18,0,561 Perry Cove,...,-0.484420,0.657620,-0.282589,370,779,56438,-1.858664,-0.494354,0.593864,-0.076304
1,1,1,-0.318757,241,4,0.230039,309,157,0,43039 Riley Greens Suite 393,...,2.039120,-2.033870,-0.293670,428,607,159395,-1.858662,2.078699,-2.030341,-0.076304
2,2,2,-0.318728,390,0,0.934149,115,381,1,594 White Dale Suite 530,...,0.717754,-1.601537,-0.280406,307,302,818703,-1.858662,0.902849,-1.592323,-0.076304
3,3,3,-0.316058,360,2,-0.158132,163,463,1,9443 Cynthia Court Apt. 038,...,1.515617,-1.590766,-0.287742,328,397,544575,-1.858660,1.662886,-1.621848,-0.076304
4,4,4,-0.318471,297,9,-0.177094,336,149,1,408 Bradley Rest,...,-0.023035,0.782279,-0.293835,116,734,831111,-1.858651,0.026941,0.841909,-0.076304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,1274786,-0.318735,499,0,-0.341769,121,332,1,162 Jessica Row Apt. 072,...,-0.161575,-1.617214,-0.293309,215,298,344658,1.757855,-0.331926,-1.558650,-0.076304
1296671,1296671,1274787,-0.314165,2,1,-0.116339,160,463,1,8617 Holmes Terrace Suite 651,...,0.143638,0.924207,-0.293832,360,630,199896,1.757855,0.072321,0.869934,-0.076304
1296672,1296672,1274788,-0.316072,599,1,0.221930,74,67,1,1632 Cohen Drive Suite 639,...,-1.102883,-1.133257,-0.291186,308,412,366013,1.757856,-0.962433,-1.082272,-0.076304
1296673,1296673,1274789,-0.316680,509,1,0.028375,179,304,1,42933 Ryan Underpass,...,0.948613,-0.895029,-0.290434,485,639,1086299,1.757861,0.832051,-0.945074,-0.076304
1296674,1296674,1274790,2.961257,370,1,-0.412005,160,404,1,135 Joseph Mountains,...,1.439314,-1.718754,-0.293441,467,895,726622,1.757862,1.571229,-1.739852,-0.076304

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df["cc_num"]=sc.fit_transform(df[["cc_num"]])
df["amt"]=sc.fit_transform(df[["amt"]])
df["zip"]=sc.fit_transform(df[["zip"]])
df["lat"]=sc.fit_transform(df[["lat"]])
df["long"]=sc.fit_transform(df[["long"]])
df["city_pop"]=sc.fit_transform(df[["city_pop"]])
df["unix_time"]=sc.fit_transform(df[["unix_time"]])
df["merch_lat"]=sc.fit_transform(df[["merch_lat"]])
df["merch_long"]=sc.fit_transform(df[["merch_long"]])
df["is_fraud"]=sc.fit_transform(df[["is_fraud"]])
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,-0.316692,514,8,-0.407826,162,18,0,561 Perry Cove,...,-0.484420,0.657620,-0.282589,370,779,56438,-1.858664,-0.494354,0.593864,-0.076304
1,1,1,-0.318757,241,4,0.230039,309,157,0,43039 Riley Greens Suite 393,...,2.039120,-2.033870,-0.293670,428,607,159395,-1.858662,2.078699,-2.030341,-0.076304
2,2,2,-0.318728,390,0,0.934149,115,381,1,594 White Dale Suite 530,...,0.717754,-1.601537,-0.280406,307,302,818703,-1.858662,0.902849,-1.592323,-0.076304
3,3,3,-0.316058,360,2,-0.158132,163,463,1,9443 Cynthia Court Apt. 038,...,1.515617,-1.590766,-0.287742,328,397,544575,-1.858660,1.662886,-1.621848,-0.076304
4,4,4,-0.318471,297,9,-0.177094,336,149,1,408 Bradley Rest,...,-0.023035,0.782279,-0.293835,116,734,831111,-1.858651,0.026941,0.841909,-0.076304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,1274786,-0.318735,499,0,-0.341769,121,332,1,162 Jessica Row Apt. 072,...,-0.161575,-1.617214,-0.293309,215,298,344658,1.757855,-0.331926,-1.558650,-0.076304
1296671,1296671,1274787,-0.314165,2,1,-0.116339,160,463,1,8617 Holmes Terrace Suite 651,...,0.143638,0.924207,-0.293832,360,630,199896,1.757855,0.072321,0.869934,-0.076304
1296672,1296672,1274788,-0.316072,599,1,0.221930,74,67,1,1632 Cohen Drive Suite 639,...,-1.102883,-1.133257,-0.291186,308,412,366013,1.757856,-0.962433,-1.082272,-0.076304
1296673,1296673,1274789,-0.316680,509,1,0.028375,179,304,1,42933 Ryan Underpass,...,0.948613,-0.895029,-0.290434,485,639,1086299,1.757861,0.832051,-0.945074,-0.076304
1296674,1296674,1274790,2.961257,370,1,-0.412005,160,404,1,135 Joseph Mountains,...,1.439314,-1.718754,-0.293441,467,895,726622,1.757862,1.571229,-1.739852,-0.076304

In [ ]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=5)
df['is_fraud']=knn.fit_transform(df[['is_fraud']])
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,-0.316692,514,8,-0.407826,162,18,0,561 Perry Cove,...,-0.484420,0.657620,-0.282589,370,779,56438,-1.858664,-0.494354,0.593864,-0.076304
1,1,1,-0.318757,241,4,0.230039,309,157,0,43039 Riley Greens Suite 393,...,2.039120,-2.033870,-0.293670,428,607,159395,-1.858662,2.078699,-2.030341,-0.076304
2,2,2,-0.318728,390,0,0.934149,115,381,1,594 White Dale Suite 530,...,0.717754,-1.601537,-0.280406,307,302,818703,-1.858662,0.902849,-1.592323,-0.076304
3,3,3,-0.316058,360,2,-0.158132,163,463,1,9443 Cynthia Court Apt. 038,...,1.515617,-1.590766,-0.287742,328,397,544575,-1.858660,1.662886,-1.621848,-0.076304
4,4,4,-0.318471,297,9,-0.177094,336,149,1,408 Bradley Rest,...,-0.023035,0.782279,-0.293835,116,734,831111,-1.858651,0.026941,0.841909,-0.076304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,1274786,-0.318735,499,0,-0.341769,121,332,1,162 Jessica Row Apt. 072,...,-0.161575,-1.617214,-0.293309,215,298,344658,1.757855,-0.331926,-1.558650,-0.076304
1296671,1296671,1274787,-0.314165,2,1,-0.116339,160,463,1,8617 Holmes Terrace Suite 651,...,0.143638,0.924207,-0.293832,360,630,199896,1.757855,0.072321,0.869934,-0.076304
1296672,1296672,1274788,-0.316072,599,1,0.221930,74,67,1,1632 Cohen Drive Suite 639,...,-1.102883,-1.133257,-0.291186,308,412,366013,1.757856,-0.962433,-1.082272,-0.076304
1296673,1296673,1274789,-0.316680,509,1,0.028375,179,304,1,42933 Ryan Underpass,...,0.948613,-0.895029,-0.290434,485,639,1086299,1.757861,0.832051,-0.945074,-0.076304
1296674,1296674,1274790,2.961257,370,1,-0.412005,160,404,1,135 Joseph Mountains,...,1.439314,-1.718754,-0.293441,467,895,726622,1.757862,1.571229,-1.739852,-0.076304

In [ ]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64